// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: envoy/config/filter/network/mongo_proxy/v3alpha/mongo_proxy.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Envoy.Config.Filter.Network.MongoProxy.V3Alpha {

  /// <summary>Holder for reflection information generated from envoy/config/filter/network/mongo_proxy/v3alpha/mongo_proxy.proto</summary>
  public static partial class MongoProxyReflection {

    #region Descriptor
    /// <summary>File descriptor for envoy/config/filter/network/mongo_proxy/v3alpha/mongo_proxy.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MongoProxyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkFlbnZveS9jb25maWcvZmlsdGVyL25ldHdvcmsvbW9uZ29fcHJveHkvdjNh",
            "bHBoYS9tb25nb19wcm94eS5wcm90bxIvZW52b3kuY29uZmlnLmZpbHRlci5u",
            "ZXR3b3JrLm1vbmdvX3Byb3h5LnYzYWxwaGEaLWVudm95L2NvbmZpZy9maWx0",
            "ZXIvZmF1bHQvdjNhbHBoYS9mYXVsdC5wcm90bxoXdmFsaWRhdGUvdmFsaWRh",
            "dGUucHJvdG8inQEKCk1vbmdvUHJveHkSHgoLc3RhdF9wcmVmaXgYASABKAlC",
            "CbrpwAMEcgIgARISCgphY2Nlc3NfbG9nGAIgASgJEjwKBWRlbGF5GAMgASgL",
            "Mi0uZW52b3kuY29uZmlnLmZpbHRlci5mYXVsdC52M2FscGhhLkZhdWx0RGVs",
            "YXkSHQoVZW1pdF9keW5hbWljX21ldGFkYXRhGAQgASgIQlIKPWlvLmVudm95",
            "cHJveHkuZW52b3kuY29uZmlnLmZpbHRlci5uZXR3b3JrLm1vbmdvX3Byb3h5",
            "LnYzYWxwaGFCD01vbmdvUHJveHlQcm90b1ABYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Envoy.Config.Filter.Fault.V3Alpha.FaultReflection.Descriptor, global::Validate.ValidateReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Config.Filter.Network.MongoProxy.V3Alpha.MongoProxy), global::Envoy.Config.Filter.Network.MongoProxy.V3Alpha.MongoProxy.Parser, new[]{ "StatPrefix", "AccessLog", "Delay", "EmitDynamicMetadata" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class MongoProxy : pb::IMessage<MongoProxy> {
    private static readonly pb::MessageParser<MongoProxy> _parser = new pb::MessageParser<MongoProxy>(() => new MongoProxy());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MongoProxy> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Envoy.Config.Filter.Network.MongoProxy.V3Alpha.MongoProxyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MongoProxy() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MongoProxy(MongoProxy other) : this() {
      statPrefix_ = other.statPrefix_;
      accessLog_ = other.accessLog_;
      delay_ = other.delay_ != null ? other.delay_.Clone() : null;
      emitDynamicMetadata_ = other.emitDynamicMetadata_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MongoProxy Clone() {
      return new MongoProxy(this);
    }

    /// <summary>Field number for the "stat_prefix" field.</summary>
    public const int StatPrefixFieldNumber = 1;
    private string statPrefix_ = "";
    /// <summary>
    /// The human readable prefix to use when emitting :ref:`statistics
    /// &lt;config_network_filters_mongo_proxy_stats>`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StatPrefix {
      get { return statPrefix_; }
      set {
        statPrefix_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "access_log" field.</summary>
    public const int AccessLogFieldNumber = 2;
    private string accessLog_ = "";
    /// <summary>
    /// The optional path to use for writing Mongo access logs. If not access log
    /// path is specified no access logs will be written. Note that access log is
    /// also gated :ref:`runtime &lt;config_network_filters_mongo_proxy_runtime>`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AccessLog {
      get { return accessLog_; }
      set {
        accessLog_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "delay" field.</summary>
    public const int DelayFieldNumber = 3;
    private global::Envoy.Config.Filter.Fault.V3Alpha.FaultDelay delay_;
    /// <summary>
    /// Inject a fixed delay before proxying a Mongo operation. Delays are
    /// applied to the following MongoDB operations: Query, Insert, GetMore,
    /// and KillCursors. Once an active delay is in progress, all incoming
    /// data up until the timer event fires will be a part of the delay.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Config.Filter.Fault.V3Alpha.FaultDelay Delay {
      get { return delay_; }
      set {
        delay_ = value;
      }
    }

    /// <summary>Field number for the "emit_dynamic_metadata" field.</summary>
    public const int EmitDynamicMetadataFieldNumber = 4;
    private bool emitDynamicMetadata_;
    /// <summary>
    /// Flag to specify whether :ref:`dynamic metadata
    /// &lt;config_network_filters_mongo_proxy_dynamic_metadata>` should be emitted. Defaults to false.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool EmitDynamicMetadata {
      get { return emitDynamicMetadata_; }
      set {
        emitDynamicMetadata_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MongoProxy);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MongoProxy other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StatPrefix != other.StatPrefix) return false;
      if (AccessLog != other.AccessLog) return false;
      if (!object.Equals(Delay, other.Delay)) return false;
      if (EmitDynamicMetadata != other.EmitDynamicMetadata) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StatPrefix.Length != 0) hash ^= StatPrefix.GetHashCode();
      if (AccessLog.Length != 0) hash ^= AccessLog.GetHashCode();
      if (delay_ != null) hash ^= Delay.GetHashCode();
      if (EmitDynamicMetadata != false) hash ^= EmitDynamicMetadata.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StatPrefix.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(StatPrefix);
      }
      if (AccessLog.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AccessLog);
      }
      if (delay_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Delay);
      }
      if (EmitDynamicMetadata != false) {
        output.WriteRawTag(32);
        output.WriteBool(EmitDynamicMetadata);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StatPrefix.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StatPrefix);
      }
      if (AccessLog.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AccessLog);
      }
      if (delay_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Delay);
      }
      if (EmitDynamicMetadata != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MongoProxy other) {
      if (other == null) {
        return;
      }
      if (other.StatPrefix.Length != 0) {
        StatPrefix = other.StatPrefix;
      }
      if (other.AccessLog.Length != 0) {
        AccessLog = other.AccessLog;
      }
      if (other.delay_ != null) {
        if (delay_ == null) {
          Delay = new global::Envoy.Config.Filter.Fault.V3Alpha.FaultDelay();
        }
        Delay.MergeFrom(other.Delay);
      }
      if (other.EmitDynamicMetadata != false) {
        EmitDynamicMetadata = other.EmitDynamicMetadata;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            StatPrefix = input.ReadString();
            break;
          }
          case 18: {
            AccessLog = input.ReadString();
            break;
          }
          case 26: {
            if (delay_ == null) {
              Delay = new global::Envoy.Config.Filter.Fault.V3Alpha.FaultDelay();
            }
            input.ReadMessage(Delay);
            break;
          }
          case 32: {
            EmitDynamicMetadata = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
