// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: envoy/data/tap/v2alpha/common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Envoy.Data.Tap.V2Alpha {

  /// <summary>Holder for reflection information generated from envoy/data/tap/v2alpha/common.proto</summary>
  public static partial class CommonReflection {

    #region Descriptor
    /// <summary>File descriptor for envoy/data/tap/v2alpha/common.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNlbnZveS9kYXRhL3RhcC92MmFscGhhL2NvbW1vbi5wcm90bxIWZW52b3ku",
            "ZGF0YS50YXAudjJhbHBoYSJPCgRCb2R5EhIKCGFzX2J5dGVzGAEgASgMSAAS",
            "EwoJYXNfc3RyaW5nGAIgASgJSAASEQoJdHJ1bmNhdGVkGAMgASgIQgsKCWJv",
            "ZHlfdHlwZUI1CiRpby5lbnZveXByb3h5LmVudm95LmRhdGEudGFwLnYyYWxw",
            "aGFCC0NvbW1vblByb3RvUAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Data.Tap.V2Alpha.Body), global::Envoy.Data.Tap.V2Alpha.Body.Parser, new[]{ "AsBytes", "AsString", "Truncated" }, new[]{ "BodyType" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Wrapper for tapped body data. This includes HTTP request/response body, transport socket received
  /// and transmitted data, etc.
  /// </summary>
  public sealed partial class Body : pb::IMessage<Body> {
    private static readonly pb::MessageParser<Body> _parser = new pb::MessageParser<Body>(() => new Body());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Body> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Envoy.Data.Tap.V2Alpha.CommonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Body() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Body(Body other) : this() {
      truncated_ = other.truncated_;
      switch (other.BodyTypeCase) {
        case BodyTypeOneofCase.AsBytes:
          AsBytes = other.AsBytes;
          break;
        case BodyTypeOneofCase.AsString:
          AsString = other.AsString;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Body Clone() {
      return new Body(this);
    }

    /// <summary>Field number for the "as_bytes" field.</summary>
    public const int AsBytesFieldNumber = 1;
    /// <summary>
    /// Body data as bytes. By default, tap body data will be present in this field, as the proto
    /// `bytes` type can contain any valid byte.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString AsBytes {
      get { return bodyTypeCase_ == BodyTypeOneofCase.AsBytes ? (pb::ByteString) bodyType_ : pb::ByteString.Empty; }
      set {
        bodyType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        bodyTypeCase_ = BodyTypeOneofCase.AsBytes;
      }
    }

    /// <summary>Field number for the "as_string" field.</summary>
    public const int AsStringFieldNumber = 2;
    /// <summary>
    /// Body data as string. This field is only used when the :ref:`JSON_BODY_AS_STRING
    /// &lt;envoy_api_enum_value_service.tap.v2alpha.OutputSink.Format.JSON_BODY_AS_STRING>` sink
    /// format type is selected. See the documentation for that option for why this is useful.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AsString {
      get { return bodyTypeCase_ == BodyTypeOneofCase.AsString ? (string) bodyType_ : ""; }
      set {
        bodyType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        bodyTypeCase_ = BodyTypeOneofCase.AsString;
      }
    }

    /// <summary>Field number for the "truncated" field.</summary>
    public const int TruncatedFieldNumber = 3;
    private bool truncated_;
    /// <summary>
    /// Specifies whether body data has been truncated to fit within the specified
    /// :ref:`max_buffered_rx_bytes
    /// &lt;envoy_api_field_service.tap.v2alpha.OutputConfig.max_buffered_rx_bytes>` and
    /// :ref:`max_buffered_tx_bytes
    /// &lt;envoy_api_field_service.tap.v2alpha.OutputConfig.max_buffered_tx_bytes>` settings.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Truncated {
      get { return truncated_; }
      set {
        truncated_ = value;
      }
    }

    private object bodyType_;
    /// <summary>Enum of possible cases for the "body_type" oneof.</summary>
    public enum BodyTypeOneofCase {
      None = 0,
      AsBytes = 1,
      AsString = 2,
    }
    private BodyTypeOneofCase bodyTypeCase_ = BodyTypeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BodyTypeOneofCase BodyTypeCase {
      get { return bodyTypeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearBodyType() {
      bodyTypeCase_ = BodyTypeOneofCase.None;
      bodyType_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Body);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Body other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AsBytes != other.AsBytes) return false;
      if (AsString != other.AsString) return false;
      if (Truncated != other.Truncated) return false;
      if (BodyTypeCase != other.BodyTypeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (bodyTypeCase_ == BodyTypeOneofCase.AsBytes) hash ^= AsBytes.GetHashCode();
      if (bodyTypeCase_ == BodyTypeOneofCase.AsString) hash ^= AsString.GetHashCode();
      if (Truncated != false) hash ^= Truncated.GetHashCode();
      hash ^= (int) bodyTypeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (bodyTypeCase_ == BodyTypeOneofCase.AsBytes) {
        output.WriteRawTag(10);
        output.WriteBytes(AsBytes);
      }
      if (bodyTypeCase_ == BodyTypeOneofCase.AsString) {
        output.WriteRawTag(18);
        output.WriteString(AsString);
      }
      if (Truncated != false) {
        output.WriteRawTag(24);
        output.WriteBool(Truncated);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (bodyTypeCase_ == BodyTypeOneofCase.AsBytes) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(AsBytes);
      }
      if (bodyTypeCase_ == BodyTypeOneofCase.AsString) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AsString);
      }
      if (Truncated != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Body other) {
      if (other == null) {
        return;
      }
      if (other.Truncated != false) {
        Truncated = other.Truncated;
      }
      switch (other.BodyTypeCase) {
        case BodyTypeOneofCase.AsBytes:
          AsBytes = other.AsBytes;
          break;
        case BodyTypeOneofCase.AsString:
          AsString = other.AsString;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            AsBytes = input.ReadBytes();
            break;
          }
          case 18: {
            AsString = input.ReadString();
            break;
          }
          case 24: {
            Truncated = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
