// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: envoy/admin/v3alpha/listeners.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Envoy.Admin.V3Alpha {

  /// <summary>Holder for reflection information generated from envoy/admin/v3alpha/listeners.proto</summary>
  public static partial class ListenersReflection {

    #region Descriptor
    /// <summary>File descriptor for envoy/admin/v3alpha/listeners.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ListenersReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNlbnZveS9hZG1pbi92M2FscGhhL2xpc3RlbmVycy5wcm90bxITZW52b3ku",
            "YWRtaW4udjNhbHBoYRokZW52b3kvYXBpL3YzYWxwaGEvY29yZS9hZGRyZXNz",
            "LnByb3RvIksKCUxpc3RlbmVycxI+ChFsaXN0ZW5lcl9zdGF0dXNlcxgBIAMo",
            "CzIjLmVudm95LmFkbWluLnYzYWxwaGEuTGlzdGVuZXJTdGF0dXMiVgoOTGlz",
            "dGVuZXJTdGF0dXMSDAoEbmFtZRgBIAEoCRI2Cg1sb2NhbF9hZGRyZXNzGAIg",
            "ASgLMh8uZW52b3kuYXBpLnYzYWxwaGEuY29yZS5BZGRyZXNzQjUKIWlvLmVu",
            "dm95cHJveHkuZW52b3kuYWRtaW4udjNhbHBoYUIOTGlzdGVuZXJzUHJvdG9Q",
            "AWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Envoy.Api.V3Alpha.Core.AddressReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Admin.V3Alpha.Listeners), global::Envoy.Admin.V3Alpha.Listeners.Parser, new[]{ "ListenerStatuses" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Admin.V3Alpha.ListenerStatus), global::Envoy.Admin.V3Alpha.ListenerStatus.Parser, new[]{ "Name", "LocalAddress" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Admin endpoint uses this wrapper for `/listeners` to display listener status information.
  /// See :ref:`/listeners &lt;operations_admin_interface_listeners>` for more information.
  /// </summary>
  public sealed partial class Listeners : pb::IMessage<Listeners> {
    private static readonly pb::MessageParser<Listeners> _parser = new pb::MessageParser<Listeners>(() => new Listeners());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Listeners> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Envoy.Admin.V3Alpha.ListenersReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Listeners() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Listeners(Listeners other) : this() {
      listenerStatuses_ = other.listenerStatuses_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Listeners Clone() {
      return new Listeners(this);
    }

    /// <summary>Field number for the "listener_statuses" field.</summary>
    public const int ListenerStatusesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Envoy.Admin.V3Alpha.ListenerStatus> _repeated_listenerStatuses_codec
        = pb::FieldCodec.ForMessage(10, global::Envoy.Admin.V3Alpha.ListenerStatus.Parser);
    private readonly pbc::RepeatedField<global::Envoy.Admin.V3Alpha.ListenerStatus> listenerStatuses_ = new pbc::RepeatedField<global::Envoy.Admin.V3Alpha.ListenerStatus>();
    /// <summary>
    /// List of listener statuses.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Envoy.Admin.V3Alpha.ListenerStatus> ListenerStatuses {
      get { return listenerStatuses_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Listeners);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Listeners other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!listenerStatuses_.Equals(other.listenerStatuses_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= listenerStatuses_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      listenerStatuses_.WriteTo(output, _repeated_listenerStatuses_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += listenerStatuses_.CalculateSize(_repeated_listenerStatuses_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Listeners other) {
      if (other == null) {
        return;
      }
      listenerStatuses_.Add(other.listenerStatuses_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            listenerStatuses_.AddEntriesFrom(input, _repeated_listenerStatuses_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Details an individual listener's current status.
  /// </summary>
  public sealed partial class ListenerStatus : pb::IMessage<ListenerStatus> {
    private static readonly pb::MessageParser<ListenerStatus> _parser = new pb::MessageParser<ListenerStatus>(() => new ListenerStatus());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ListenerStatus> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Envoy.Admin.V3Alpha.ListenersReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListenerStatus() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListenerStatus(ListenerStatus other) : this() {
      name_ = other.name_;
      localAddress_ = other.localAddress_ != null ? other.localAddress_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListenerStatus Clone() {
      return new ListenerStatus(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    /// <summary>
    /// Name of the listener
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "local_address" field.</summary>
    public const int LocalAddressFieldNumber = 2;
    private global::Envoy.Api.V3Alpha.Core.Address localAddress_;
    /// <summary>
    /// The actual local address that the listener is listening on. If a listener was configured
    /// to listen on port 0, then this address has the port that was allocated by the OS.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Api.V3Alpha.Core.Address LocalAddress {
      get { return localAddress_; }
      set {
        localAddress_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ListenerStatus);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ListenerStatus other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (!object.Equals(LocalAddress, other.LocalAddress)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (localAddress_ != null) hash ^= LocalAddress.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (localAddress_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(LocalAddress);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (localAddress_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LocalAddress);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ListenerStatus other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.localAddress_ != null) {
        if (localAddress_ == null) {
          LocalAddress = new global::Envoy.Api.V3Alpha.Core.Address();
        }
        LocalAddress.MergeFrom(other.LocalAddress);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            if (localAddress_ == null) {
              LocalAddress = new global::Envoy.Api.V3Alpha.Core.Address();
            }
            input.ReadMessage(LocalAddress);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
