// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: envoy/service/tap/v3alpha/common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Envoy.Service.Tap.V3Alpha {

  /// <summary>Holder for reflection information generated from envoy/service/tap/v3alpha/common.proto</summary>
  public static partial class CommonReflection {

    #region Descriptor
    /// <summary>File descriptor for envoy/service/tap/v3alpha/common.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZlbnZveS9zZXJ2aWNlL3RhcC92M2FscGhhL2NvbW1vbi5wcm90bxIZZW52",
            "b3kuc2VydmljZS50YXAudjNhbHBoYRojZW52b3kvYXBpL3YzYWxwaGEvcm91",
            "dGUvcm91dGUucHJvdG8aIWVudm95L2FwaS92M2FscGhhL2NvcmUvYmFzZS5w",
            "cm90bxopZW52b3kvYXBpL3YzYWxwaGEvY29yZS9ncnBjX3NlcnZpY2UucHJv",
            "dG8aHmdvb2dsZS9wcm90b2J1Zi93cmFwcGVycy5wcm90bxoXdmFsaWRhdGUv",
            "dmFsaWRhdGUucHJvdG8i6wEKCVRhcENvbmZpZxJLCgxtYXRjaF9jb25maWcY",
            "ASABKAsyKS5lbnZveS5zZXJ2aWNlLnRhcC52M2FscGhhLk1hdGNoUHJlZGlj",
            "YXRlQgq66cADBYoBAhABEkoKDW91dHB1dF9jb25maWcYAiABKAsyJy5lbnZv",
            "eS5zZXJ2aWNlLnRhcC52M2FscGhhLk91dHB1dENvbmZpZ0IKuunAAwWKAQIQ",
            "ARJFCgt0YXBfZW5hYmxlZBgDIAEoCzIwLmVudm95LmFwaS52M2FscGhhLmNv",
            "cmUuUnVudGltZUZyYWN0aW9uYWxQZXJjZW50IrIFCg5NYXRjaFByZWRpY2F0",
            "ZRJGCghvcl9tYXRjaBgBIAEoCzIyLmVudm95LnNlcnZpY2UudGFwLnYzYWxw",
            "aGEuTWF0Y2hQcmVkaWNhdGUuTWF0Y2hTZXRIABJHCglhbmRfbWF0Y2gYAiAB",
            "KAsyMi5lbnZveS5zZXJ2aWNlLnRhcC52M2FscGhhLk1hdGNoUHJlZGljYXRl",
            "Lk1hdGNoU2V0SAASPgoJbm90X21hdGNoGAMgASgLMikuZW52b3kuc2Vydmlj",
            "ZS50YXAudjNhbHBoYS5NYXRjaFByZWRpY2F0ZUgAEh4KCWFueV9tYXRjaBgE",
            "IAEoCEIJuunAAwRqAggBSAASUQoaaHR0cF9yZXF1ZXN0X2hlYWRlcnNfbWF0",
            "Y2gYBSABKAsyKy5lbnZveS5zZXJ2aWNlLnRhcC52M2FscGhhLkh0dHBIZWFk",
            "ZXJzTWF0Y2hIABJSChtodHRwX3JlcXVlc3RfdHJhaWxlcnNfbWF0Y2gYBiAB",
            "KAsyKy5lbnZveS5zZXJ2aWNlLnRhcC52M2FscGhhLkh0dHBIZWFkZXJzTWF0",
            "Y2hIABJSChtodHRwX3Jlc3BvbnNlX2hlYWRlcnNfbWF0Y2gYByABKAsyKy5l",
            "bnZveS5zZXJ2aWNlLnRhcC52M2FscGhhLkh0dHBIZWFkZXJzTWF0Y2hIABJT",
            "ChxodHRwX3Jlc3BvbnNlX3RyYWlsZXJzX21hdGNoGAggASgLMisuZW52b3ku",
            "c2VydmljZS50YXAudjNhbHBoYS5IdHRwSGVhZGVyc01hdGNoSAAaUAoITWF0",
            "Y2hTZXQSRAoFcnVsZXMYASADKAsyKS5lbnZveS5zZXJ2aWNlLnRhcC52M2Fs",
            "cGhhLk1hdGNoUHJlZGljYXRlQgq66cADBZIBAggCQg0KBHJ1bGUSBbjpwAMB",
            "IksKEEh0dHBIZWFkZXJzTWF0Y2gSNwoHaGVhZGVycxgBIAMoCzImLmVudm95",
            "LmFwaS52M2FscGhhLnJvdXRlLkhlYWRlck1hdGNoZXIi3wEKDE91dHB1dENv",
            "bmZpZxJCCgVzaW5rcxgBIAMoCzIlLmVudm95LnNlcnZpY2UudGFwLnYzYWxw",
            "aGEuT3V0cHV0U2lua0IMuunAAweSAQQIARABEjsKFW1heF9idWZmZXJlZF9y",
            "eF9ieXRlcxgCIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5VSW50MzJWYWx1ZRI7",
            "ChVtYXhfYnVmZmVyZWRfdHhfYnl0ZXMYAyABKAsyHC5nb29nbGUucHJvdG9i",
            "dWYuVUludDMyVmFsdWUSEQoJc3RyZWFtaW5nGAQgASgIIsYDCgpPdXRwdXRT",
            "aW5rEkgKBmZvcm1hdBgBIAEoDjIsLmVudm95LnNlcnZpY2UudGFwLnYzYWxw",
            "aGEuT3V0cHV0U2luay5Gb3JtYXRCCrrpwAMFggECEAESSAoPc3RyZWFtaW5n",
            "X2FkbWluGAIgASgLMi0uZW52b3kuc2VydmljZS50YXAudjNhbHBoYS5TdHJl",
            "YW1pbmdBZG1pblNpbmtIABJBCgxmaWxlX3Blcl90YXAYAyABKAsyKS5lbnZv",
            "eS5zZXJ2aWNlLnRhcC52M2FscGhhLkZpbGVQZXJUYXBTaW5rSAASRgoOc3Ry",
            "ZWFtaW5nX2dycGMYBCABKAsyLC5lbnZveS5zZXJ2aWNlLnRhcC52M2FscGhh",
            "LlN0cmVhbWluZ0dycGNTaW5rSAAifgoGRm9ybWF0EhYKEkpTT05fQk9EWV9B",
            "U19CWVRFUxAAEhcKE0pTT05fQk9EWV9BU19TVFJJTkcQARIQCgxQUk9UT19C",
            "SU5BUlkQAhIhCh1QUk9UT19CSU5BUllfTEVOR1RIX0RFTElNSVRFRBADEg4K",
            "ClBST1RPX1RFWFQQBEIZChBvdXRwdXRfc2lua190eXBlEgW46cADASIUChJT",
            "dHJlYW1pbmdBZG1pblNpbmsiMAoORmlsZVBlclRhcFNpbmsSHgoLcGF0aF9w",
            "cmVmaXgYASABKAlCCbrpwAMEcgIgASJqChFTdHJlYW1pbmdHcnBjU2luaxIO",
            "CgZ0YXBfaWQYASABKAkSRQoMZ3JwY19zZXJ2aWNlGAIgASgLMiMuZW52b3ku",
            "YXBpLnYzYWxwaGEuY29yZS5HcnBjU2VydmljZUIKuunAAwWKAQIQAUI4Cidp",
            "by5lbnZveXByb3h5LmVudm95LnNlcnZpY2UudGFwLnYzYWxwaGFCC0NvbW1v",
            "blByb3RvUAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Envoy.Api.V3Alpha.Route.RouteReflection.Descriptor, global::Envoy.Api.V3Alpha.Core.BaseReflection.Descriptor, global::Envoy.Api.V3Alpha.Core.GrpcServiceReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, global::Validate.ValidateReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Service.Tap.V3Alpha.TapConfig), global::Envoy.Service.Tap.V3Alpha.TapConfig.Parser, new[]{ "MatchConfig", "OutputConfig", "TapEnabled" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Service.Tap.V3Alpha.MatchPredicate), global::Envoy.Service.Tap.V3Alpha.MatchPredicate.Parser, new[]{ "OrMatch", "AndMatch", "NotMatch", "AnyMatch", "HttpRequestHeadersMatch", "HttpRequestTrailersMatch", "HttpResponseHeadersMatch", "HttpResponseTrailersMatch" }, new[]{ "Rule" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Service.Tap.V3Alpha.MatchPredicate.Types.MatchSet), global::Envoy.Service.Tap.V3Alpha.MatchPredicate.Types.MatchSet.Parser, new[]{ "Rules" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Service.Tap.V3Alpha.HttpHeadersMatch), global::Envoy.Service.Tap.V3Alpha.HttpHeadersMatch.Parser, new[]{ "Headers" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Service.Tap.V3Alpha.OutputConfig), global::Envoy.Service.Tap.V3Alpha.OutputConfig.Parser, new[]{ "Sinks", "MaxBufferedRxBytes", "MaxBufferedTxBytes", "Streaming" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Service.Tap.V3Alpha.OutputSink), global::Envoy.Service.Tap.V3Alpha.OutputSink.Parser, new[]{ "Format", "StreamingAdmin", "FilePerTap", "StreamingGrpc" }, new[]{ "OutputSinkType" }, new[]{ typeof(global::Envoy.Service.Tap.V3Alpha.OutputSink.Types.Format) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Service.Tap.V3Alpha.StreamingAdminSink), global::Envoy.Service.Tap.V3Alpha.StreamingAdminSink.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Service.Tap.V3Alpha.FilePerTapSink), global::Envoy.Service.Tap.V3Alpha.FilePerTapSink.Parser, new[]{ "PathPrefix" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Service.Tap.V3Alpha.StreamingGrpcSink), global::Envoy.Service.Tap.V3Alpha.StreamingGrpcSink.Parser, new[]{ "TapId", "GrpcService" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Tap configuration.
  /// </summary>
  public sealed partial class TapConfig : pb::IMessage<TapConfig> {
    private static readonly pb::MessageParser<TapConfig> _parser = new pb::MessageParser<TapConfig>(() => new TapConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TapConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Envoy.Service.Tap.V3Alpha.CommonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TapConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TapConfig(TapConfig other) : this() {
      matchConfig_ = other.matchConfig_ != null ? other.matchConfig_.Clone() : null;
      outputConfig_ = other.outputConfig_ != null ? other.outputConfig_.Clone() : null;
      tapEnabled_ = other.tapEnabled_ != null ? other.tapEnabled_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TapConfig Clone() {
      return new TapConfig(this);
    }

    /// <summary>Field number for the "match_config" field.</summary>
    public const int MatchConfigFieldNumber = 1;
    private global::Envoy.Service.Tap.V3Alpha.MatchPredicate matchConfig_;
    /// <summary>
    /// The match configuration. If the configuration matches the data source being tapped, a tap will
    /// occur, with the result written to the configured output.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Service.Tap.V3Alpha.MatchPredicate MatchConfig {
      get { return matchConfig_; }
      set {
        matchConfig_ = value;
      }
    }

    /// <summary>Field number for the "output_config" field.</summary>
    public const int OutputConfigFieldNumber = 2;
    private global::Envoy.Service.Tap.V3Alpha.OutputConfig outputConfig_;
    /// <summary>
    /// The tap output configuration. If a match configuration matches a data source being tapped,
    /// a tap will occur and the data will be written to the configured output.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Service.Tap.V3Alpha.OutputConfig OutputConfig {
      get { return outputConfig_; }
      set {
        outputConfig_ = value;
      }
    }

    /// <summary>Field number for the "tap_enabled" field.</summary>
    public const int TapEnabledFieldNumber = 3;
    private global::Envoy.Api.V3Alpha.Core.RuntimeFractionalPercent tapEnabled_;
    /// <summary>
    /// [#not-implemented-hide:] Specify if Tap matching is enabled. The % of requests\connections for
    /// which the tap matching is enabled. When not enabled, the request\connection will not be
    /// recorded.
    ///
    /// .. note::
    ///
    ///   This field defaults to 100/:ref:`HUNDRED
    ///   &lt;envoy_api_enum_type.FractionalPercent.DenominatorType>`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Api.V3Alpha.Core.RuntimeFractionalPercent TapEnabled {
      get { return tapEnabled_; }
      set {
        tapEnabled_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TapConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TapConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(MatchConfig, other.MatchConfig)) return false;
      if (!object.Equals(OutputConfig, other.OutputConfig)) return false;
      if (!object.Equals(TapEnabled, other.TapEnabled)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (matchConfig_ != null) hash ^= MatchConfig.GetHashCode();
      if (outputConfig_ != null) hash ^= OutputConfig.GetHashCode();
      if (tapEnabled_ != null) hash ^= TapEnabled.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (matchConfig_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(MatchConfig);
      }
      if (outputConfig_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(OutputConfig);
      }
      if (tapEnabled_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(TapEnabled);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (matchConfig_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MatchConfig);
      }
      if (outputConfig_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OutputConfig);
      }
      if (tapEnabled_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TapEnabled);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TapConfig other) {
      if (other == null) {
        return;
      }
      if (other.matchConfig_ != null) {
        if (matchConfig_ == null) {
          MatchConfig = new global::Envoy.Service.Tap.V3Alpha.MatchPredicate();
        }
        MatchConfig.MergeFrom(other.MatchConfig);
      }
      if (other.outputConfig_ != null) {
        if (outputConfig_ == null) {
          OutputConfig = new global::Envoy.Service.Tap.V3Alpha.OutputConfig();
        }
        OutputConfig.MergeFrom(other.OutputConfig);
      }
      if (other.tapEnabled_ != null) {
        if (tapEnabled_ == null) {
          TapEnabled = new global::Envoy.Api.V3Alpha.Core.RuntimeFractionalPercent();
        }
        TapEnabled.MergeFrom(other.TapEnabled);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (matchConfig_ == null) {
              MatchConfig = new global::Envoy.Service.Tap.V3Alpha.MatchPredicate();
            }
            input.ReadMessage(MatchConfig);
            break;
          }
          case 18: {
            if (outputConfig_ == null) {
              OutputConfig = new global::Envoy.Service.Tap.V3Alpha.OutputConfig();
            }
            input.ReadMessage(OutputConfig);
            break;
          }
          case 26: {
            if (tapEnabled_ == null) {
              TapEnabled = new global::Envoy.Api.V3Alpha.Core.RuntimeFractionalPercent();
            }
            input.ReadMessage(TapEnabled);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Tap match configuration. This is a recursive structure which allows complex nested match
  /// configurations to be built using various logical operators.
  /// </summary>
  public sealed partial class MatchPredicate : pb::IMessage<MatchPredicate> {
    private static readonly pb::MessageParser<MatchPredicate> _parser = new pb::MessageParser<MatchPredicate>(() => new MatchPredicate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MatchPredicate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Envoy.Service.Tap.V3Alpha.CommonReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MatchPredicate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MatchPredicate(MatchPredicate other) : this() {
      switch (other.RuleCase) {
        case RuleOneofCase.OrMatch:
          OrMatch = other.OrMatch.Clone();
          break;
        case RuleOneofCase.AndMatch:
          AndMatch = other.AndMatch.Clone();
          break;
        case RuleOneofCase.NotMatch:
          NotMatch = other.NotMatch.Clone();
          break;
        case RuleOneofCase.AnyMatch:
          AnyMatch = other.AnyMatch;
          break;
        case RuleOneofCase.HttpRequestHeadersMatch:
          HttpRequestHeadersMatch = other.HttpRequestHeadersMatch.Clone();
          break;
        case RuleOneofCase.HttpRequestTrailersMatch:
          HttpRequestTrailersMatch = other.HttpRequestTrailersMatch.Clone();
          break;
        case RuleOneofCase.HttpResponseHeadersMatch:
          HttpResponseHeadersMatch = other.HttpResponseHeadersMatch.Clone();
          break;
        case RuleOneofCase.HttpResponseTrailersMatch:
          HttpResponseTrailersMatch = other.HttpResponseTrailersMatch.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MatchPredicate Clone() {
      return new MatchPredicate(this);
    }

    /// <summary>Field number for the "or_match" field.</summary>
    public const int OrMatchFieldNumber = 1;
    /// <summary>
    /// A set that describes a logical OR. If any member of the set matches, the match configuration
    /// matches.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Service.Tap.V3Alpha.MatchPredicate.Types.MatchSet OrMatch {
      get { return ruleCase_ == RuleOneofCase.OrMatch ? (global::Envoy.Service.Tap.V3Alpha.MatchPredicate.Types.MatchSet) rule_ : null; }
      set {
        rule_ = value;
        ruleCase_ = value == null ? RuleOneofCase.None : RuleOneofCase.OrMatch;
      }
    }

    /// <summary>Field number for the "and_match" field.</summary>
    public const int AndMatchFieldNumber = 2;
    /// <summary>
    /// A set that describes a logical AND. If all members of the set match, the match configuration
    /// matches.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Service.Tap.V3Alpha.MatchPredicate.Types.MatchSet AndMatch {
      get { return ruleCase_ == RuleOneofCase.AndMatch ? (global::Envoy.Service.Tap.V3Alpha.MatchPredicate.Types.MatchSet) rule_ : null; }
      set {
        rule_ = value;
        ruleCase_ = value == null ? RuleOneofCase.None : RuleOneofCase.AndMatch;
      }
    }

    /// <summary>Field number for the "not_match" field.</summary>
    public const int NotMatchFieldNumber = 3;
    /// <summary>
    /// A negation match. The match configuration will match if the negated match condition matches.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Service.Tap.V3Alpha.MatchPredicate NotMatch {
      get { return ruleCase_ == RuleOneofCase.NotMatch ? (global::Envoy.Service.Tap.V3Alpha.MatchPredicate) rule_ : null; }
      set {
        rule_ = value;
        ruleCase_ = value == null ? RuleOneofCase.None : RuleOneofCase.NotMatch;
      }
    }

    /// <summary>Field number for the "any_match" field.</summary>
    public const int AnyMatchFieldNumber = 4;
    /// <summary>
    /// The match configuration will always match.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool AnyMatch {
      get { return ruleCase_ == RuleOneofCase.AnyMatch ? (bool) rule_ : false; }
      set {
        rule_ = value;
        ruleCase_ = RuleOneofCase.AnyMatch;
      }
    }

    /// <summary>Field number for the "http_request_headers_match" field.</summary>
    public const int HttpRequestHeadersMatchFieldNumber = 5;
    /// <summary>
    /// HTTP request headers match configuration.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Service.Tap.V3Alpha.HttpHeadersMatch HttpRequestHeadersMatch {
      get { return ruleCase_ == RuleOneofCase.HttpRequestHeadersMatch ? (global::Envoy.Service.Tap.V3Alpha.HttpHeadersMatch) rule_ : null; }
      set {
        rule_ = value;
        ruleCase_ = value == null ? RuleOneofCase.None : RuleOneofCase.HttpRequestHeadersMatch;
      }
    }

    /// <summary>Field number for the "http_request_trailers_match" field.</summary>
    public const int HttpRequestTrailersMatchFieldNumber = 6;
    /// <summary>
    /// HTTP request trailers match configuration.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Service.Tap.V3Alpha.HttpHeadersMatch HttpRequestTrailersMatch {
      get { return ruleCase_ == RuleOneofCase.HttpRequestTrailersMatch ? (global::Envoy.Service.Tap.V3Alpha.HttpHeadersMatch) rule_ : null; }
      set {
        rule_ = value;
        ruleCase_ = value == null ? RuleOneofCase.None : RuleOneofCase.HttpRequestTrailersMatch;
      }
    }

    /// <summary>Field number for the "http_response_headers_match" field.</summary>
    public const int HttpResponseHeadersMatchFieldNumber = 7;
    /// <summary>
    /// HTTP response headers match configuration.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Service.Tap.V3Alpha.HttpHeadersMatch HttpResponseHeadersMatch {
      get { return ruleCase_ == RuleOneofCase.HttpResponseHeadersMatch ? (global::Envoy.Service.Tap.V3Alpha.HttpHeadersMatch) rule_ : null; }
      set {
        rule_ = value;
        ruleCase_ = value == null ? RuleOneofCase.None : RuleOneofCase.HttpResponseHeadersMatch;
      }
    }

    /// <summary>Field number for the "http_response_trailers_match" field.</summary>
    public const int HttpResponseTrailersMatchFieldNumber = 8;
    /// <summary>
    /// HTTP response trailers match configuration.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Service.Tap.V3Alpha.HttpHeadersMatch HttpResponseTrailersMatch {
      get { return ruleCase_ == RuleOneofCase.HttpResponseTrailersMatch ? (global::Envoy.Service.Tap.V3Alpha.HttpHeadersMatch) rule_ : null; }
      set {
        rule_ = value;
        ruleCase_ = value == null ? RuleOneofCase.None : RuleOneofCase.HttpResponseTrailersMatch;
      }
    }

    private object rule_;
    /// <summary>Enum of possible cases for the "rule" oneof.</summary>
    public enum RuleOneofCase {
      None = 0,
      OrMatch = 1,
      AndMatch = 2,
      NotMatch = 3,
      AnyMatch = 4,
      HttpRequestHeadersMatch = 5,
      HttpRequestTrailersMatch = 6,
      HttpResponseHeadersMatch = 7,
      HttpResponseTrailersMatch = 8,
    }
    private RuleOneofCase ruleCase_ = RuleOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RuleOneofCase RuleCase {
      get { return ruleCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearRule() {
      ruleCase_ = RuleOneofCase.None;
      rule_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MatchPredicate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MatchPredicate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(OrMatch, other.OrMatch)) return false;
      if (!object.Equals(AndMatch, other.AndMatch)) return false;
      if (!object.Equals(NotMatch, other.NotMatch)) return false;
      if (AnyMatch != other.AnyMatch) return false;
      if (!object.Equals(HttpRequestHeadersMatch, other.HttpRequestHeadersMatch)) return false;
      if (!object.Equals(HttpRequestTrailersMatch, other.HttpRequestTrailersMatch)) return false;
      if (!object.Equals(HttpResponseHeadersMatch, other.HttpResponseHeadersMatch)) return false;
      if (!object.Equals(HttpResponseTrailersMatch, other.HttpResponseTrailersMatch)) return false;
      if (RuleCase != other.RuleCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ruleCase_ == RuleOneofCase.OrMatch) hash ^= OrMatch.GetHashCode();
      if (ruleCase_ == RuleOneofCase.AndMatch) hash ^= AndMatch.GetHashCode();
      if (ruleCase_ == RuleOneofCase.NotMatch) hash ^= NotMatch.GetHashCode();
      if (ruleCase_ == RuleOneofCase.AnyMatch) hash ^= AnyMatch.GetHashCode();
      if (ruleCase_ == RuleOneofCase.HttpRequestHeadersMatch) hash ^= HttpRequestHeadersMatch.GetHashCode();
      if (ruleCase_ == RuleOneofCase.HttpRequestTrailersMatch) hash ^= HttpRequestTrailersMatch.GetHashCode();
      if (ruleCase_ == RuleOneofCase.HttpResponseHeadersMatch) hash ^= HttpResponseHeadersMatch.GetHashCode();
      if (ruleCase_ == RuleOneofCase.HttpResponseTrailersMatch) hash ^= HttpResponseTrailersMatch.GetHashCode();
      hash ^= (int) ruleCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ruleCase_ == RuleOneofCase.OrMatch) {
        output.WriteRawTag(10);
        output.WriteMessage(OrMatch);
      }
      if (ruleCase_ == RuleOneofCase.AndMatch) {
        output.WriteRawTag(18);
        output.WriteMessage(AndMatch);
      }
      if (ruleCase_ == RuleOneofCase.NotMatch) {
        output.WriteRawTag(26);
        output.WriteMessage(NotMatch);
      }
      if (ruleCase_ == RuleOneofCase.AnyMatch) {
        output.WriteRawTag(32);
        output.WriteBool(AnyMatch);
      }
      if (ruleCase_ == RuleOneofCase.HttpRequestHeadersMatch) {
        output.WriteRawTag(42);
        output.WriteMessage(HttpRequestHeadersMatch);
      }
      if (ruleCase_ == RuleOneofCase.HttpRequestTrailersMatch) {
        output.WriteRawTag(50);
        output.WriteMessage(HttpRequestTrailersMatch);
      }
      if (ruleCase_ == RuleOneofCase.HttpResponseHeadersMatch) {
        output.WriteRawTag(58);
        output.WriteMessage(HttpResponseHeadersMatch);
      }
      if (ruleCase_ == RuleOneofCase.HttpResponseTrailersMatch) {
        output.WriteRawTag(66);
        output.WriteMessage(HttpResponseTrailersMatch);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ruleCase_ == RuleOneofCase.OrMatch) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OrMatch);
      }
      if (ruleCase_ == RuleOneofCase.AndMatch) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AndMatch);
      }
      if (ruleCase_ == RuleOneofCase.NotMatch) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NotMatch);
      }
      if (ruleCase_ == RuleOneofCase.AnyMatch) {
        size += 1 + 1;
      }
      if (ruleCase_ == RuleOneofCase.HttpRequestHeadersMatch) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HttpRequestHeadersMatch);
      }
      if (ruleCase_ == RuleOneofCase.HttpRequestTrailersMatch) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HttpRequestTrailersMatch);
      }
      if (ruleCase_ == RuleOneofCase.HttpResponseHeadersMatch) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HttpResponseHeadersMatch);
      }
      if (ruleCase_ == RuleOneofCase.HttpResponseTrailersMatch) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HttpResponseTrailersMatch);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MatchPredicate other) {
      if (other == null) {
        return;
      }
      switch (other.RuleCase) {
        case RuleOneofCase.OrMatch:
          if (OrMatch == null) {
            OrMatch = new global::Envoy.Service.Tap.V3Alpha.MatchPredicate.Types.MatchSet();
          }
          OrMatch.MergeFrom(other.OrMatch);
          break;
        case RuleOneofCase.AndMatch:
          if (AndMatch == null) {
            AndMatch = new global::Envoy.Service.Tap.V3Alpha.MatchPredicate.Types.MatchSet();
          }
          AndMatch.MergeFrom(other.AndMatch);
          break;
        case RuleOneofCase.NotMatch:
          if (NotMatch == null) {
            NotMatch = new global::Envoy.Service.Tap.V3Alpha.MatchPredicate();
          }
          NotMatch.MergeFrom(other.NotMatch);
          break;
        case RuleOneofCase.AnyMatch:
          AnyMatch = other.AnyMatch;
          break;
        case RuleOneofCase.HttpRequestHeadersMatch:
          if (HttpRequestHeadersMatch == null) {
            HttpRequestHeadersMatch = new global::Envoy.Service.Tap.V3Alpha.HttpHeadersMatch();
          }
          HttpRequestHeadersMatch.MergeFrom(other.HttpRequestHeadersMatch);
          break;
        case RuleOneofCase.HttpRequestTrailersMatch:
          if (HttpRequestTrailersMatch == null) {
            HttpRequestTrailersMatch = new global::Envoy.Service.Tap.V3Alpha.HttpHeadersMatch();
          }
          HttpRequestTrailersMatch.MergeFrom(other.HttpRequestTrailersMatch);
          break;
        case RuleOneofCase.HttpResponseHeadersMatch:
          if (HttpResponseHeadersMatch == null) {
            HttpResponseHeadersMatch = new global::Envoy.Service.Tap.V3Alpha.HttpHeadersMatch();
          }
          HttpResponseHeadersMatch.MergeFrom(other.HttpResponseHeadersMatch);
          break;
        case RuleOneofCase.HttpResponseTrailersMatch:
          if (HttpResponseTrailersMatch == null) {
            HttpResponseTrailersMatch = new global::Envoy.Service.Tap.V3Alpha.HttpHeadersMatch();
          }
          HttpResponseTrailersMatch.MergeFrom(other.HttpResponseTrailersMatch);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Envoy.Service.Tap.V3Alpha.MatchPredicate.Types.MatchSet subBuilder = new global::Envoy.Service.Tap.V3Alpha.MatchPredicate.Types.MatchSet();
            if (ruleCase_ == RuleOneofCase.OrMatch) {
              subBuilder.MergeFrom(OrMatch);
            }
            input.ReadMessage(subBuilder);
            OrMatch = subBuilder;
            break;
          }
          case 18: {
            global::Envoy.Service.Tap.V3Alpha.MatchPredicate.Types.MatchSet subBuilder = new global::Envoy.Service.Tap.V3Alpha.MatchPredicate.Types.MatchSet();
            if (ruleCase_ == RuleOneofCase.AndMatch) {
              subBuilder.MergeFrom(AndMatch);
            }
            input.ReadMessage(subBuilder);
            AndMatch = subBuilder;
            break;
          }
          case 26: {
            global::Envoy.Service.Tap.V3Alpha.MatchPredicate subBuilder = new global::Envoy.Service.Tap.V3Alpha.MatchPredicate();
            if (ruleCase_ == RuleOneofCase.NotMatch) {
              subBuilder.MergeFrom(NotMatch);
            }
            input.ReadMessage(subBuilder);
            NotMatch = subBuilder;
            break;
          }
          case 32: {
            AnyMatch = input.ReadBool();
            break;
          }
          case 42: {
            global::Envoy.Service.Tap.V3Alpha.HttpHeadersMatch subBuilder = new global::Envoy.Service.Tap.V3Alpha.HttpHeadersMatch();
            if (ruleCase_ == RuleOneofCase.HttpRequestHeadersMatch) {
              subBuilder.MergeFrom(HttpRequestHeadersMatch);
            }
            input.ReadMessage(subBuilder);
            HttpRequestHeadersMatch = subBuilder;
            break;
          }
          case 50: {
            global::Envoy.Service.Tap.V3Alpha.HttpHeadersMatch subBuilder = new global::Envoy.Service.Tap.V3Alpha.HttpHeadersMatch();
            if (ruleCase_ == RuleOneofCase.HttpRequestTrailersMatch) {
              subBuilder.MergeFrom(HttpRequestTrailersMatch);
            }
            input.ReadMessage(subBuilder);
            HttpRequestTrailersMatch = subBuilder;
            break;
          }
          case 58: {
            global::Envoy.Service.Tap.V3Alpha.HttpHeadersMatch subBuilder = new global::Envoy.Service.Tap.V3Alpha.HttpHeadersMatch();
            if (ruleCase_ == RuleOneofCase.HttpResponseHeadersMatch) {
              subBuilder.MergeFrom(HttpResponseHeadersMatch);
            }
            input.ReadMessage(subBuilder);
            HttpResponseHeadersMatch = subBuilder;
            break;
          }
          case 66: {
            global::Envoy.Service.Tap.V3Alpha.HttpHeadersMatch subBuilder = new global::Envoy.Service.Tap.V3Alpha.HttpHeadersMatch();
            if (ruleCase_ == RuleOneofCase.HttpResponseTrailersMatch) {
              subBuilder.MergeFrom(HttpResponseTrailersMatch);
            }
            input.ReadMessage(subBuilder);
            HttpResponseTrailersMatch = subBuilder;
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the MatchPredicate message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      /// <summary>
      /// A set of match configurations used for logical operations.
      /// </summary>
      public sealed partial class MatchSet : pb::IMessage<MatchSet> {
        private static readonly pb::MessageParser<MatchSet> _parser = new pb::MessageParser<MatchSet>(() => new MatchSet());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<MatchSet> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Envoy.Service.Tap.V3Alpha.MatchPredicate.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public MatchSet() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public MatchSet(MatchSet other) : this() {
          rules_ = other.rules_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public MatchSet Clone() {
          return new MatchSet(this);
        }

        /// <summary>Field number for the "rules" field.</summary>
        public const int RulesFieldNumber = 1;
        private static readonly pb::FieldCodec<global::Envoy.Service.Tap.V3Alpha.MatchPredicate> _repeated_rules_codec
            = pb::FieldCodec.ForMessage(10, global::Envoy.Service.Tap.V3Alpha.MatchPredicate.Parser);
        private readonly pbc::RepeatedField<global::Envoy.Service.Tap.V3Alpha.MatchPredicate> rules_ = new pbc::RepeatedField<global::Envoy.Service.Tap.V3Alpha.MatchPredicate>();
        /// <summary>
        /// The list of rules that make up the set.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<global::Envoy.Service.Tap.V3Alpha.MatchPredicate> Rules {
          get { return rules_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as MatchSet);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(MatchSet other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if(!rules_.Equals(other.rules_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          hash ^= rules_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          rules_.WriteTo(output, _repeated_rules_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          size += rules_.CalculateSize(_repeated_rules_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(MatchSet other) {
          if (other == null) {
            return;
          }
          rules_.Add(other.rules_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                rules_.AddEntriesFrom(input, _repeated_rules_codec);
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  /// <summary>
  /// HTTP headers match configuration.
  /// </summary>
  public sealed partial class HttpHeadersMatch : pb::IMessage<HttpHeadersMatch> {
    private static readonly pb::MessageParser<HttpHeadersMatch> _parser = new pb::MessageParser<HttpHeadersMatch>(() => new HttpHeadersMatch());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<HttpHeadersMatch> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Envoy.Service.Tap.V3Alpha.CommonReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HttpHeadersMatch() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HttpHeadersMatch(HttpHeadersMatch other) : this() {
      headers_ = other.headers_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HttpHeadersMatch Clone() {
      return new HttpHeadersMatch(this);
    }

    /// <summary>Field number for the "headers" field.</summary>
    public const int HeadersFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Envoy.Api.V3Alpha.Route.HeaderMatcher> _repeated_headers_codec
        = pb::FieldCodec.ForMessage(10, global::Envoy.Api.V3Alpha.Route.HeaderMatcher.Parser);
    private readonly pbc::RepeatedField<global::Envoy.Api.V3Alpha.Route.HeaderMatcher> headers_ = new pbc::RepeatedField<global::Envoy.Api.V3Alpha.Route.HeaderMatcher>();
    /// <summary>
    /// HTTP headers to match.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Envoy.Api.V3Alpha.Route.HeaderMatcher> Headers {
      get { return headers_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as HttpHeadersMatch);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(HttpHeadersMatch other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!headers_.Equals(other.headers_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= headers_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      headers_.WriteTo(output, _repeated_headers_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += headers_.CalculateSize(_repeated_headers_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(HttpHeadersMatch other) {
      if (other == null) {
        return;
      }
      headers_.Add(other.headers_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            headers_.AddEntriesFrom(input, _repeated_headers_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Tap output configuration.
  /// </summary>
  public sealed partial class OutputConfig : pb::IMessage<OutputConfig> {
    private static readonly pb::MessageParser<OutputConfig> _parser = new pb::MessageParser<OutputConfig>(() => new OutputConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OutputConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Envoy.Service.Tap.V3Alpha.CommonReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OutputConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OutputConfig(OutputConfig other) : this() {
      sinks_ = other.sinks_.Clone();
      MaxBufferedRxBytes = other.MaxBufferedRxBytes;
      MaxBufferedTxBytes = other.MaxBufferedTxBytes;
      streaming_ = other.streaming_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OutputConfig Clone() {
      return new OutputConfig(this);
    }

    /// <summary>Field number for the "sinks" field.</summary>
    public const int SinksFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Envoy.Service.Tap.V3Alpha.OutputSink> _repeated_sinks_codec
        = pb::FieldCodec.ForMessage(10, global::Envoy.Service.Tap.V3Alpha.OutputSink.Parser);
    private readonly pbc::RepeatedField<global::Envoy.Service.Tap.V3Alpha.OutputSink> sinks_ = new pbc::RepeatedField<global::Envoy.Service.Tap.V3Alpha.OutputSink>();
    /// <summary>
    /// Output sinks for tap data. Currently a single sink is allowed in the list. Once multiple
    /// sink types are supported this constraint will be relaxed.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Envoy.Service.Tap.V3Alpha.OutputSink> Sinks {
      get { return sinks_; }
    }

    /// <summary>Field number for the "max_buffered_rx_bytes" field.</summary>
    public const int MaxBufferedRxBytesFieldNumber = 2;
    private static readonly pb::FieldCodec<uint?> _single_maxBufferedRxBytes_codec = pb::FieldCodec.ForStructWrapper<uint>(18);
    private uint? maxBufferedRxBytes_;
    /// <summary>
    /// For buffered tapping, the maximum amount of received body that will be buffered prior to
    /// truncation. If truncation occurs, the :ref:`truncated
    /// &lt;envoy_api_field_data.tap.v3alpha.Body.truncated>` field will be set. If not specified, the
    /// default is 1KiB.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint? MaxBufferedRxBytes {
      get { return maxBufferedRxBytes_; }
      set {
        maxBufferedRxBytes_ = value;
      }
    }


    /// <summary>Field number for the "max_buffered_tx_bytes" field.</summary>
    public const int MaxBufferedTxBytesFieldNumber = 3;
    private static readonly pb::FieldCodec<uint?> _single_maxBufferedTxBytes_codec = pb::FieldCodec.ForStructWrapper<uint>(26);
    private uint? maxBufferedTxBytes_;
    /// <summary>
    /// For buffered tapping, the maximum amount of transmitted body that will be buffered prior to
    /// truncation. If truncation occurs, the :ref:`truncated
    /// &lt;envoy_api_field_data.tap.v3alpha.Body.truncated>` field will be set. If not specified, the
    /// default is 1KiB.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint? MaxBufferedTxBytes {
      get { return maxBufferedTxBytes_; }
      set {
        maxBufferedTxBytes_ = value;
      }
    }


    /// <summary>Field number for the "streaming" field.</summary>
    public const int StreamingFieldNumber = 4;
    private bool streaming_;
    /// <summary>
    /// Indicates whether taps produce a single buffered message per tap, or multiple streamed
    /// messages per tap in the emitted :ref:`TraceWrapper
    /// &lt;envoy_api_msg_data.tap.v3alpha.TraceWrapper>` messages. Note that streamed tapping does not
    /// mean that no buffering takes place. Buffering may be required if data is processed before a
    /// match can be determined. See the HTTP tap filter :ref:`streaming
    /// &lt;config_http_filters_tap_streaming>` documentation for more information.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Streaming {
      get { return streaming_; }
      set {
        streaming_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OutputConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OutputConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!sinks_.Equals(other.sinks_)) return false;
      if (MaxBufferedRxBytes != other.MaxBufferedRxBytes) return false;
      if (MaxBufferedTxBytes != other.MaxBufferedTxBytes) return false;
      if (Streaming != other.Streaming) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= sinks_.GetHashCode();
      if (maxBufferedRxBytes_ != null) hash ^= MaxBufferedRxBytes.GetHashCode();
      if (maxBufferedTxBytes_ != null) hash ^= MaxBufferedTxBytes.GetHashCode();
      if (Streaming != false) hash ^= Streaming.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      sinks_.WriteTo(output, _repeated_sinks_codec);
      if (maxBufferedRxBytes_ != null) {
        _single_maxBufferedRxBytes_codec.WriteTagAndValue(output, MaxBufferedRxBytes);
      }
      if (maxBufferedTxBytes_ != null) {
        _single_maxBufferedTxBytes_codec.WriteTagAndValue(output, MaxBufferedTxBytes);
      }
      if (Streaming != false) {
        output.WriteRawTag(32);
        output.WriteBool(Streaming);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += sinks_.CalculateSize(_repeated_sinks_codec);
      if (maxBufferedRxBytes_ != null) {
        size += _single_maxBufferedRxBytes_codec.CalculateSizeWithTag(MaxBufferedRxBytes);
      }
      if (maxBufferedTxBytes_ != null) {
        size += _single_maxBufferedTxBytes_codec.CalculateSizeWithTag(MaxBufferedTxBytes);
      }
      if (Streaming != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OutputConfig other) {
      if (other == null) {
        return;
      }
      sinks_.Add(other.sinks_);
      if (other.maxBufferedRxBytes_ != null) {
        if (maxBufferedRxBytes_ == null || other.MaxBufferedRxBytes != 0) {
          MaxBufferedRxBytes = other.MaxBufferedRxBytes;
        }
      }
      if (other.maxBufferedTxBytes_ != null) {
        if (maxBufferedTxBytes_ == null || other.MaxBufferedTxBytes != 0) {
          MaxBufferedTxBytes = other.MaxBufferedTxBytes;
        }
      }
      if (other.Streaming != false) {
        Streaming = other.Streaming;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            sinks_.AddEntriesFrom(input, _repeated_sinks_codec);
            break;
          }
          case 18: {
            uint? value = _single_maxBufferedRxBytes_codec.Read(input);
            if (maxBufferedRxBytes_ == null || value != 0) {
              MaxBufferedRxBytes = value;
            }
            break;
          }
          case 26: {
            uint? value = _single_maxBufferedTxBytes_codec.Read(input);
            if (maxBufferedTxBytes_ == null || value != 0) {
              MaxBufferedTxBytes = value;
            }
            break;
          }
          case 32: {
            Streaming = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Tap output sink configuration.
  /// </summary>
  public sealed partial class OutputSink : pb::IMessage<OutputSink> {
    private static readonly pb::MessageParser<OutputSink> _parser = new pb::MessageParser<OutputSink>(() => new OutputSink());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OutputSink> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Envoy.Service.Tap.V3Alpha.CommonReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OutputSink() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OutputSink(OutputSink other) : this() {
      format_ = other.format_;
      switch (other.OutputSinkTypeCase) {
        case OutputSinkTypeOneofCase.StreamingAdmin:
          StreamingAdmin = other.StreamingAdmin.Clone();
          break;
        case OutputSinkTypeOneofCase.FilePerTap:
          FilePerTap = other.FilePerTap.Clone();
          break;
        case OutputSinkTypeOneofCase.StreamingGrpc:
          StreamingGrpc = other.StreamingGrpc.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OutputSink Clone() {
      return new OutputSink(this);
    }

    /// <summary>Field number for the "format" field.</summary>
    public const int FormatFieldNumber = 1;
    private global::Envoy.Service.Tap.V3Alpha.OutputSink.Types.Format format_ = global::Envoy.Service.Tap.V3Alpha.OutputSink.Types.Format.JsonBodyAsBytes;
    /// <summary>
    /// Sink output format.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Service.Tap.V3Alpha.OutputSink.Types.Format Format {
      get { return format_; }
      set {
        format_ = value;
      }
    }

    /// <summary>Field number for the "streaming_admin" field.</summary>
    public const int StreamingAdminFieldNumber = 2;
    /// <summary>
    /// Tap output will be streamed out the :http:post:`/tap` admin endpoint.
    ///
    /// .. attention::
    ///
    ///   It is only allowed to specify the streaming admin output sink if the tap is being
    ///   configured from the :http:post:`/tap` admin endpoint. Thus, if an extension has
    ///   been configured to receive tap configuration from some other source (e.g., static
    ///   file, XDS, etc.) configuring the streaming admin output type will fail.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Service.Tap.V3Alpha.StreamingAdminSink StreamingAdmin {
      get { return outputSinkTypeCase_ == OutputSinkTypeOneofCase.StreamingAdmin ? (global::Envoy.Service.Tap.V3Alpha.StreamingAdminSink) outputSinkType_ : null; }
      set {
        outputSinkType_ = value;
        outputSinkTypeCase_ = value == null ? OutputSinkTypeOneofCase.None : OutputSinkTypeOneofCase.StreamingAdmin;
      }
    }

    /// <summary>Field number for the "file_per_tap" field.</summary>
    public const int FilePerTapFieldNumber = 3;
    /// <summary>
    /// Tap output will be written to a file per tap sink.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Service.Tap.V3Alpha.FilePerTapSink FilePerTap {
      get { return outputSinkTypeCase_ == OutputSinkTypeOneofCase.FilePerTap ? (global::Envoy.Service.Tap.V3Alpha.FilePerTapSink) outputSinkType_ : null; }
      set {
        outputSinkType_ = value;
        outputSinkTypeCase_ = value == null ? OutputSinkTypeOneofCase.None : OutputSinkTypeOneofCase.FilePerTap;
      }
    }

    /// <summary>Field number for the "streaming_grpc" field.</summary>
    public const int StreamingGrpcFieldNumber = 4;
    /// <summary>
    /// [#not-implemented-hide:]
    /// GrpcService to stream data to. The format argument must be PROTO_BINARY.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Service.Tap.V3Alpha.StreamingGrpcSink StreamingGrpc {
      get { return outputSinkTypeCase_ == OutputSinkTypeOneofCase.StreamingGrpc ? (global::Envoy.Service.Tap.V3Alpha.StreamingGrpcSink) outputSinkType_ : null; }
      set {
        outputSinkType_ = value;
        outputSinkTypeCase_ = value == null ? OutputSinkTypeOneofCase.None : OutputSinkTypeOneofCase.StreamingGrpc;
      }
    }

    private object outputSinkType_;
    /// <summary>Enum of possible cases for the "output_sink_type" oneof.</summary>
    public enum OutputSinkTypeOneofCase {
      None = 0,
      StreamingAdmin = 2,
      FilePerTap = 3,
      StreamingGrpc = 4,
    }
    private OutputSinkTypeOneofCase outputSinkTypeCase_ = OutputSinkTypeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OutputSinkTypeOneofCase OutputSinkTypeCase {
      get { return outputSinkTypeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearOutputSinkType() {
      outputSinkTypeCase_ = OutputSinkTypeOneofCase.None;
      outputSinkType_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OutputSink);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OutputSink other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Format != other.Format) return false;
      if (!object.Equals(StreamingAdmin, other.StreamingAdmin)) return false;
      if (!object.Equals(FilePerTap, other.FilePerTap)) return false;
      if (!object.Equals(StreamingGrpc, other.StreamingGrpc)) return false;
      if (OutputSinkTypeCase != other.OutputSinkTypeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Format != global::Envoy.Service.Tap.V3Alpha.OutputSink.Types.Format.JsonBodyAsBytes) hash ^= Format.GetHashCode();
      if (outputSinkTypeCase_ == OutputSinkTypeOneofCase.StreamingAdmin) hash ^= StreamingAdmin.GetHashCode();
      if (outputSinkTypeCase_ == OutputSinkTypeOneofCase.FilePerTap) hash ^= FilePerTap.GetHashCode();
      if (outputSinkTypeCase_ == OutputSinkTypeOneofCase.StreamingGrpc) hash ^= StreamingGrpc.GetHashCode();
      hash ^= (int) outputSinkTypeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Format != global::Envoy.Service.Tap.V3Alpha.OutputSink.Types.Format.JsonBodyAsBytes) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Format);
      }
      if (outputSinkTypeCase_ == OutputSinkTypeOneofCase.StreamingAdmin) {
        output.WriteRawTag(18);
        output.WriteMessage(StreamingAdmin);
      }
      if (outputSinkTypeCase_ == OutputSinkTypeOneofCase.FilePerTap) {
        output.WriteRawTag(26);
        output.WriteMessage(FilePerTap);
      }
      if (outputSinkTypeCase_ == OutputSinkTypeOneofCase.StreamingGrpc) {
        output.WriteRawTag(34);
        output.WriteMessage(StreamingGrpc);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Format != global::Envoy.Service.Tap.V3Alpha.OutputSink.Types.Format.JsonBodyAsBytes) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Format);
      }
      if (outputSinkTypeCase_ == OutputSinkTypeOneofCase.StreamingAdmin) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StreamingAdmin);
      }
      if (outputSinkTypeCase_ == OutputSinkTypeOneofCase.FilePerTap) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FilePerTap);
      }
      if (outputSinkTypeCase_ == OutputSinkTypeOneofCase.StreamingGrpc) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StreamingGrpc);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OutputSink other) {
      if (other == null) {
        return;
      }
      if (other.Format != global::Envoy.Service.Tap.V3Alpha.OutputSink.Types.Format.JsonBodyAsBytes) {
        Format = other.Format;
      }
      switch (other.OutputSinkTypeCase) {
        case OutputSinkTypeOneofCase.StreamingAdmin:
          if (StreamingAdmin == null) {
            StreamingAdmin = new global::Envoy.Service.Tap.V3Alpha.StreamingAdminSink();
          }
          StreamingAdmin.MergeFrom(other.StreamingAdmin);
          break;
        case OutputSinkTypeOneofCase.FilePerTap:
          if (FilePerTap == null) {
            FilePerTap = new global::Envoy.Service.Tap.V3Alpha.FilePerTapSink();
          }
          FilePerTap.MergeFrom(other.FilePerTap);
          break;
        case OutputSinkTypeOneofCase.StreamingGrpc:
          if (StreamingGrpc == null) {
            StreamingGrpc = new global::Envoy.Service.Tap.V3Alpha.StreamingGrpcSink();
          }
          StreamingGrpc.MergeFrom(other.StreamingGrpc);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Format = (global::Envoy.Service.Tap.V3Alpha.OutputSink.Types.Format) input.ReadEnum();
            break;
          }
          case 18: {
            global::Envoy.Service.Tap.V3Alpha.StreamingAdminSink subBuilder = new global::Envoy.Service.Tap.V3Alpha.StreamingAdminSink();
            if (outputSinkTypeCase_ == OutputSinkTypeOneofCase.StreamingAdmin) {
              subBuilder.MergeFrom(StreamingAdmin);
            }
            input.ReadMessage(subBuilder);
            StreamingAdmin = subBuilder;
            break;
          }
          case 26: {
            global::Envoy.Service.Tap.V3Alpha.FilePerTapSink subBuilder = new global::Envoy.Service.Tap.V3Alpha.FilePerTapSink();
            if (outputSinkTypeCase_ == OutputSinkTypeOneofCase.FilePerTap) {
              subBuilder.MergeFrom(FilePerTap);
            }
            input.ReadMessage(subBuilder);
            FilePerTap = subBuilder;
            break;
          }
          case 34: {
            global::Envoy.Service.Tap.V3Alpha.StreamingGrpcSink subBuilder = new global::Envoy.Service.Tap.V3Alpha.StreamingGrpcSink();
            if (outputSinkTypeCase_ == OutputSinkTypeOneofCase.StreamingGrpc) {
              subBuilder.MergeFrom(StreamingGrpc);
            }
            input.ReadMessage(subBuilder);
            StreamingGrpc = subBuilder;
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the OutputSink message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      /// <summary>
      /// Output format. All output is in the form of one or more :ref:`TraceWrapper
      /// &lt;envoy_api_msg_data.tap.v3alpha.TraceWrapper>` messages. This enumeration indicates
      /// how those messages are written. Note that not all sinks support all output formats. See
      /// individual sink documentation for more information.
      /// </summary>
      public enum Format {
        /// <summary>
        /// Each message will be written as JSON. Any :ref:`body &lt;envoy_api_msg_data.tap.v3alpha.Body>`
        /// data will be present in the :ref:`as_bytes
        /// &lt;envoy_api_field_data.tap.v3alpha.Body.as_bytes>` field. This means that body data will be
        /// base64 encoded as per the `proto3 JSON mappings
        /// &lt;https://developers.google.com/protocol-buffers/docs/proto3#json>`_.
        /// </summary>
        [pbr::OriginalName("JSON_BODY_AS_BYTES")] JsonBodyAsBytes = 0,
        /// <summary>
        /// Each message will be written as JSON. Any :ref:`body &lt;envoy_api_msg_data.tap.v3alpha.Body>`
        /// data will be present in the :ref:`as_string
        /// &lt;envoy_api_field_data.tap.v3alpha.Body.as_string>` field. This means that body data will be
        /// string encoded as per the `proto3 JSON mappings
        /// &lt;https://developers.google.com/protocol-buffers/docs/proto3#json>`_. This format type is
        /// useful when it is known that that body is human readable (e.g., JSON over HTTP) and the
        /// user wishes to view it directly without being forced to base64 decode the body.
        /// </summary>
        [pbr::OriginalName("JSON_BODY_AS_STRING")] JsonBodyAsString = 1,
        /// <summary>
        /// Binary proto format. Note that binary proto is not self-delimiting. If a sink writes
        /// multiple binary messages without any length information the data stream will not be
        /// useful. However, for certain sinks that are self-delimiting (e.g., one message per file)
        /// this output format makes consumption simpler.
        /// </summary>
        [pbr::OriginalName("PROTO_BINARY")] ProtoBinary = 2,
        /// <summary>
        /// Messages are written as a sequence tuples, where each tuple is the message length encoded
        /// as a `protobuf 32-bit varint
        /// &lt;https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.io.coded_stream>`_
        /// followed by the binary message. The messages can be read back using the language specific
        /// protobuf coded stream implementation to obtain the message length and the message.
        /// </summary>
        [pbr::OriginalName("PROTO_BINARY_LENGTH_DELIMITED")] ProtoBinaryLengthDelimited = 3,
        /// <summary>
        /// Text proto format.
        /// </summary>
        [pbr::OriginalName("PROTO_TEXT")] ProtoText = 4,
      }

    }
    #endregion

  }

  /// <summary>
  /// Streaming admin sink configuration.
  /// </summary>
  public sealed partial class StreamingAdminSink : pb::IMessage<StreamingAdminSink> {
    private static readonly pb::MessageParser<StreamingAdminSink> _parser = new pb::MessageParser<StreamingAdminSink>(() => new StreamingAdminSink());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StreamingAdminSink> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Envoy.Service.Tap.V3Alpha.CommonReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StreamingAdminSink() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StreamingAdminSink(StreamingAdminSink other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StreamingAdminSink Clone() {
      return new StreamingAdminSink(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StreamingAdminSink);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StreamingAdminSink other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StreamingAdminSink other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  /// <summary>
  /// The file per tap sink outputs a discrete file for every tapped stream.
  /// </summary>
  public sealed partial class FilePerTapSink : pb::IMessage<FilePerTapSink> {
    private static readonly pb::MessageParser<FilePerTapSink> _parser = new pb::MessageParser<FilePerTapSink>(() => new FilePerTapSink());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FilePerTapSink> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Envoy.Service.Tap.V3Alpha.CommonReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FilePerTapSink() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FilePerTapSink(FilePerTapSink other) : this() {
      pathPrefix_ = other.pathPrefix_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FilePerTapSink Clone() {
      return new FilePerTapSink(this);
    }

    /// <summary>Field number for the "path_prefix" field.</summary>
    public const int PathPrefixFieldNumber = 1;
    private string pathPrefix_ = "";
    /// <summary>
    /// Path prefix. The output file will be of the form &lt;path_prefix>_&lt;id>.pb, where &lt;id> is an
    /// identifier distinguishing the recorded trace for stream instances (the Envoy
    /// connection ID, HTTP stream ID, etc.).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PathPrefix {
      get { return pathPrefix_; }
      set {
        pathPrefix_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FilePerTapSink);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FilePerTapSink other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PathPrefix != other.PathPrefix) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PathPrefix.Length != 0) hash ^= PathPrefix.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PathPrefix.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PathPrefix);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PathPrefix.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PathPrefix);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FilePerTapSink other) {
      if (other == null) {
        return;
      }
      if (other.PathPrefix.Length != 0) {
        PathPrefix = other.PathPrefix;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PathPrefix = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// [#not-implemented-hide:] Streaming gRPC sink configuration sends the taps to an external gRPC
  /// server.
  /// </summary>
  public sealed partial class StreamingGrpcSink : pb::IMessage<StreamingGrpcSink> {
    private static readonly pb::MessageParser<StreamingGrpcSink> _parser = new pb::MessageParser<StreamingGrpcSink>(() => new StreamingGrpcSink());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StreamingGrpcSink> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Envoy.Service.Tap.V3Alpha.CommonReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StreamingGrpcSink() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StreamingGrpcSink(StreamingGrpcSink other) : this() {
      tapId_ = other.tapId_;
      grpcService_ = other.grpcService_ != null ? other.grpcService_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StreamingGrpcSink Clone() {
      return new StreamingGrpcSink(this);
    }

    /// <summary>Field number for the "tap_id" field.</summary>
    public const int TapIdFieldNumber = 1;
    private string tapId_ = "";
    /// <summary>
    /// Opaque identifier, that will be sent back to the streaming grpc server.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TapId {
      get { return tapId_; }
      set {
        tapId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "grpc_service" field.</summary>
    public const int GrpcServiceFieldNumber = 2;
    private global::Envoy.Api.V3Alpha.Core.GrpcService grpcService_;
    /// <summary>
    /// The gRPC server that hosts the Tap Sink Service.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Api.V3Alpha.Core.GrpcService GrpcService {
      get { return grpcService_; }
      set {
        grpcService_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StreamingGrpcSink);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StreamingGrpcSink other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TapId != other.TapId) return false;
      if (!object.Equals(GrpcService, other.GrpcService)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TapId.Length != 0) hash ^= TapId.GetHashCode();
      if (grpcService_ != null) hash ^= GrpcService.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TapId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TapId);
      }
      if (grpcService_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(GrpcService);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TapId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TapId);
      }
      if (grpcService_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GrpcService);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StreamingGrpcSink other) {
      if (other == null) {
        return;
      }
      if (other.TapId.Length != 0) {
        TapId = other.TapId;
      }
      if (other.grpcService_ != null) {
        if (grpcService_ == null) {
          GrpcService = new global::Envoy.Api.V3Alpha.Core.GrpcService();
        }
        GrpcService.MergeFrom(other.GrpcService);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TapId = input.ReadString();
            break;
          }
          case 18: {
            if (grpcService_ == null) {
              GrpcService = new global::Envoy.Api.V3Alpha.Core.GrpcService();
            }
            input.ReadMessage(GrpcService);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
