// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: envoy/type/matcher/value.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Envoy.Type.Matcher {

  /// <summary>Holder for reflection information generated from envoy/type/matcher/value.proto</summary>
  public static partial class ValueReflection {

    #region Descriptor
    /// <summary>File descriptor for envoy/type/matcher/value.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ValueReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5lbnZveS90eXBlL21hdGNoZXIvdmFsdWUucHJvdG8SEmVudm95LnR5cGUu",
            "bWF0Y2hlchofZW52b3kvdHlwZS9tYXRjaGVyL251bWJlci5wcm90bxofZW52",
            "b3kvdHlwZS9tYXRjaGVyL3N0cmluZy5wcm90bxoXdmFsaWRhdGUvdmFsaWRh",
            "dGUucHJvdG8i0QIKDFZhbHVlTWF0Y2hlchJACgpudWxsX21hdGNoGAEgASgL",
            "MiouZW52b3kudHlwZS5tYXRjaGVyLlZhbHVlTWF0Y2hlci5OdWxsTWF0Y2hI",
            "ABI5Cgxkb3VibGVfbWF0Y2gYAiABKAsyIS5lbnZveS50eXBlLm1hdGNoZXIu",
            "RG91YmxlTWF0Y2hlckgAEjkKDHN0cmluZ19tYXRjaBgDIAEoCzIhLmVudm95",
            "LnR5cGUubWF0Y2hlci5TdHJpbmdNYXRjaGVySAASFAoKYm9vbF9tYXRjaBgE",
            "IAEoCEgAEhcKDXByZXNlbnRfbWF0Y2gYBSABKAhIABI1CgpsaXN0X21hdGNo",
            "GAYgASgLMh8uZW52b3kudHlwZS5tYXRjaGVyLkxpc3RNYXRjaGVySAAaCwoJ",
            "TnVsbE1hdGNoQhYKDW1hdGNoX3BhdHRlcm4SBbjpwAMBIlkKC0xpc3RNYXRj",
            "aGVyEjIKBm9uZV9vZhgBIAEoCzIgLmVudm95LnR5cGUubWF0Y2hlci5WYWx1",
            "ZU1hdGNoZXJIAEIWCg1tYXRjaF9wYXR0ZXJuEgW46cADAUIwCiBpby5lbnZv",
            "eXByb3h5LmVudm95LnR5cGUubWF0Y2hlckIKVmFsdWVQcm90b1ABYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Envoy.Type.Matcher.NumberReflection.Descriptor, global::Envoy.Type.Matcher.StringReflection.Descriptor, global::Validate.ValidateReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Type.Matcher.ValueMatcher), global::Envoy.Type.Matcher.ValueMatcher.Parser, new[]{ "NullMatch", "DoubleMatch", "StringMatch", "BoolMatch", "PresentMatch", "ListMatch" }, new[]{ "MatchPattern" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Type.Matcher.ValueMatcher.Types.NullMatch), global::Envoy.Type.Matcher.ValueMatcher.Types.NullMatch.Parser, null, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Type.Matcher.ListMatcher), global::Envoy.Type.Matcher.ListMatcher.Parser, new[]{ "OneOf" }, new[]{ "MatchPattern" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Specifies the way to match a ProtobufWkt::Value. Primitive values and ListValue are supported.
  /// StructValue is not supported and is always not matched.
  /// </summary>
  public sealed partial class ValueMatcher : pb::IMessage<ValueMatcher> {
    private static readonly pb::MessageParser<ValueMatcher> _parser = new pb::MessageParser<ValueMatcher>(() => new ValueMatcher());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ValueMatcher> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Envoy.Type.Matcher.ValueReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ValueMatcher() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ValueMatcher(ValueMatcher other) : this() {
      switch (other.MatchPatternCase) {
        case MatchPatternOneofCase.NullMatch:
          NullMatch = other.NullMatch.Clone();
          break;
        case MatchPatternOneofCase.DoubleMatch:
          DoubleMatch = other.DoubleMatch.Clone();
          break;
        case MatchPatternOneofCase.StringMatch:
          StringMatch = other.StringMatch.Clone();
          break;
        case MatchPatternOneofCase.BoolMatch:
          BoolMatch = other.BoolMatch;
          break;
        case MatchPatternOneofCase.PresentMatch:
          PresentMatch = other.PresentMatch;
          break;
        case MatchPatternOneofCase.ListMatch:
          ListMatch = other.ListMatch.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ValueMatcher Clone() {
      return new ValueMatcher(this);
    }

    /// <summary>Field number for the "null_match" field.</summary>
    public const int NullMatchFieldNumber = 1;
    /// <summary>
    /// If specified, a match occurs if and only if the target value is a NullValue.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Type.Matcher.ValueMatcher.Types.NullMatch NullMatch {
      get { return matchPatternCase_ == MatchPatternOneofCase.NullMatch ? (global::Envoy.Type.Matcher.ValueMatcher.Types.NullMatch) matchPattern_ : null; }
      set {
        matchPattern_ = value;
        matchPatternCase_ = value == null ? MatchPatternOneofCase.None : MatchPatternOneofCase.NullMatch;
      }
    }

    /// <summary>Field number for the "double_match" field.</summary>
    public const int DoubleMatchFieldNumber = 2;
    /// <summary>
    /// If specified, a match occurs if and only if the target value is a double value and is
    /// matched to this field.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Type.Matcher.DoubleMatcher DoubleMatch {
      get { return matchPatternCase_ == MatchPatternOneofCase.DoubleMatch ? (global::Envoy.Type.Matcher.DoubleMatcher) matchPattern_ : null; }
      set {
        matchPattern_ = value;
        matchPatternCase_ = value == null ? MatchPatternOneofCase.None : MatchPatternOneofCase.DoubleMatch;
      }
    }

    /// <summary>Field number for the "string_match" field.</summary>
    public const int StringMatchFieldNumber = 3;
    /// <summary>
    /// If specified, a match occurs if and only if the target value is a string value and is
    /// matched to this field.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Type.Matcher.StringMatcher StringMatch {
      get { return matchPatternCase_ == MatchPatternOneofCase.StringMatch ? (global::Envoy.Type.Matcher.StringMatcher) matchPattern_ : null; }
      set {
        matchPattern_ = value;
        matchPatternCase_ = value == null ? MatchPatternOneofCase.None : MatchPatternOneofCase.StringMatch;
      }
    }

    /// <summary>Field number for the "bool_match" field.</summary>
    public const int BoolMatchFieldNumber = 4;
    /// <summary>
    /// If specified, a match occurs if and only if the target value is a bool value and is equal
    /// to this field.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool BoolMatch {
      get { return matchPatternCase_ == MatchPatternOneofCase.BoolMatch ? (bool) matchPattern_ : false; }
      set {
        matchPattern_ = value;
        matchPatternCase_ = MatchPatternOneofCase.BoolMatch;
      }
    }

    /// <summary>Field number for the "present_match" field.</summary>
    public const int PresentMatchFieldNumber = 5;
    /// <summary>
    /// If specified, value match will be performed based on whether the path is referring to a
    /// valid primitive value in the metadata. If the path is referring to a non-primitive value,
    /// the result is always not matched.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool PresentMatch {
      get { return matchPatternCase_ == MatchPatternOneofCase.PresentMatch ? (bool) matchPattern_ : false; }
      set {
        matchPattern_ = value;
        matchPatternCase_ = MatchPatternOneofCase.PresentMatch;
      }
    }

    /// <summary>Field number for the "list_match" field.</summary>
    public const int ListMatchFieldNumber = 6;
    /// <summary>
    /// If specified, a match occurs if and only if the target value is a list value and
    /// is matched to this field.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Type.Matcher.ListMatcher ListMatch {
      get { return matchPatternCase_ == MatchPatternOneofCase.ListMatch ? (global::Envoy.Type.Matcher.ListMatcher) matchPattern_ : null; }
      set {
        matchPattern_ = value;
        matchPatternCase_ = value == null ? MatchPatternOneofCase.None : MatchPatternOneofCase.ListMatch;
      }
    }

    private object matchPattern_;
    /// <summary>Enum of possible cases for the "match_pattern" oneof.</summary>
    public enum MatchPatternOneofCase {
      None = 0,
      NullMatch = 1,
      DoubleMatch = 2,
      StringMatch = 3,
      BoolMatch = 4,
      PresentMatch = 5,
      ListMatch = 6,
    }
    private MatchPatternOneofCase matchPatternCase_ = MatchPatternOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MatchPatternOneofCase MatchPatternCase {
      get { return matchPatternCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearMatchPattern() {
      matchPatternCase_ = MatchPatternOneofCase.None;
      matchPattern_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ValueMatcher);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ValueMatcher other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(NullMatch, other.NullMatch)) return false;
      if (!object.Equals(DoubleMatch, other.DoubleMatch)) return false;
      if (!object.Equals(StringMatch, other.StringMatch)) return false;
      if (BoolMatch != other.BoolMatch) return false;
      if (PresentMatch != other.PresentMatch) return false;
      if (!object.Equals(ListMatch, other.ListMatch)) return false;
      if (MatchPatternCase != other.MatchPatternCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (matchPatternCase_ == MatchPatternOneofCase.NullMatch) hash ^= NullMatch.GetHashCode();
      if (matchPatternCase_ == MatchPatternOneofCase.DoubleMatch) hash ^= DoubleMatch.GetHashCode();
      if (matchPatternCase_ == MatchPatternOneofCase.StringMatch) hash ^= StringMatch.GetHashCode();
      if (matchPatternCase_ == MatchPatternOneofCase.BoolMatch) hash ^= BoolMatch.GetHashCode();
      if (matchPatternCase_ == MatchPatternOneofCase.PresentMatch) hash ^= PresentMatch.GetHashCode();
      if (matchPatternCase_ == MatchPatternOneofCase.ListMatch) hash ^= ListMatch.GetHashCode();
      hash ^= (int) matchPatternCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (matchPatternCase_ == MatchPatternOneofCase.NullMatch) {
        output.WriteRawTag(10);
        output.WriteMessage(NullMatch);
      }
      if (matchPatternCase_ == MatchPatternOneofCase.DoubleMatch) {
        output.WriteRawTag(18);
        output.WriteMessage(DoubleMatch);
      }
      if (matchPatternCase_ == MatchPatternOneofCase.StringMatch) {
        output.WriteRawTag(26);
        output.WriteMessage(StringMatch);
      }
      if (matchPatternCase_ == MatchPatternOneofCase.BoolMatch) {
        output.WriteRawTag(32);
        output.WriteBool(BoolMatch);
      }
      if (matchPatternCase_ == MatchPatternOneofCase.PresentMatch) {
        output.WriteRawTag(40);
        output.WriteBool(PresentMatch);
      }
      if (matchPatternCase_ == MatchPatternOneofCase.ListMatch) {
        output.WriteRawTag(50);
        output.WriteMessage(ListMatch);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (matchPatternCase_ == MatchPatternOneofCase.NullMatch) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NullMatch);
      }
      if (matchPatternCase_ == MatchPatternOneofCase.DoubleMatch) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DoubleMatch);
      }
      if (matchPatternCase_ == MatchPatternOneofCase.StringMatch) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StringMatch);
      }
      if (matchPatternCase_ == MatchPatternOneofCase.BoolMatch) {
        size += 1 + 1;
      }
      if (matchPatternCase_ == MatchPatternOneofCase.PresentMatch) {
        size += 1 + 1;
      }
      if (matchPatternCase_ == MatchPatternOneofCase.ListMatch) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ListMatch);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ValueMatcher other) {
      if (other == null) {
        return;
      }
      switch (other.MatchPatternCase) {
        case MatchPatternOneofCase.NullMatch:
          if (NullMatch == null) {
            NullMatch = new global::Envoy.Type.Matcher.ValueMatcher.Types.NullMatch();
          }
          NullMatch.MergeFrom(other.NullMatch);
          break;
        case MatchPatternOneofCase.DoubleMatch:
          if (DoubleMatch == null) {
            DoubleMatch = new global::Envoy.Type.Matcher.DoubleMatcher();
          }
          DoubleMatch.MergeFrom(other.DoubleMatch);
          break;
        case MatchPatternOneofCase.StringMatch:
          if (StringMatch == null) {
            StringMatch = new global::Envoy.Type.Matcher.StringMatcher();
          }
          StringMatch.MergeFrom(other.StringMatch);
          break;
        case MatchPatternOneofCase.BoolMatch:
          BoolMatch = other.BoolMatch;
          break;
        case MatchPatternOneofCase.PresentMatch:
          PresentMatch = other.PresentMatch;
          break;
        case MatchPatternOneofCase.ListMatch:
          if (ListMatch == null) {
            ListMatch = new global::Envoy.Type.Matcher.ListMatcher();
          }
          ListMatch.MergeFrom(other.ListMatch);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Envoy.Type.Matcher.ValueMatcher.Types.NullMatch subBuilder = new global::Envoy.Type.Matcher.ValueMatcher.Types.NullMatch();
            if (matchPatternCase_ == MatchPatternOneofCase.NullMatch) {
              subBuilder.MergeFrom(NullMatch);
            }
            input.ReadMessage(subBuilder);
            NullMatch = subBuilder;
            break;
          }
          case 18: {
            global::Envoy.Type.Matcher.DoubleMatcher subBuilder = new global::Envoy.Type.Matcher.DoubleMatcher();
            if (matchPatternCase_ == MatchPatternOneofCase.DoubleMatch) {
              subBuilder.MergeFrom(DoubleMatch);
            }
            input.ReadMessage(subBuilder);
            DoubleMatch = subBuilder;
            break;
          }
          case 26: {
            global::Envoy.Type.Matcher.StringMatcher subBuilder = new global::Envoy.Type.Matcher.StringMatcher();
            if (matchPatternCase_ == MatchPatternOneofCase.StringMatch) {
              subBuilder.MergeFrom(StringMatch);
            }
            input.ReadMessage(subBuilder);
            StringMatch = subBuilder;
            break;
          }
          case 32: {
            BoolMatch = input.ReadBool();
            break;
          }
          case 40: {
            PresentMatch = input.ReadBool();
            break;
          }
          case 50: {
            global::Envoy.Type.Matcher.ListMatcher subBuilder = new global::Envoy.Type.Matcher.ListMatcher();
            if (matchPatternCase_ == MatchPatternOneofCase.ListMatch) {
              subBuilder.MergeFrom(ListMatch);
            }
            input.ReadMessage(subBuilder);
            ListMatch = subBuilder;
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the ValueMatcher message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      /// <summary>
      /// NullMatch is an empty message to specify a null value.
      /// </summary>
      public sealed partial class NullMatch : pb::IMessage<NullMatch> {
        private static readonly pb::MessageParser<NullMatch> _parser = new pb::MessageParser<NullMatch>(() => new NullMatch());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<NullMatch> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Envoy.Type.Matcher.ValueMatcher.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public NullMatch() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public NullMatch(NullMatch other) : this() {
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public NullMatch Clone() {
          return new NullMatch(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as NullMatch);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(NullMatch other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(NullMatch other) {
          if (other == null) {
            return;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
            }
          }
        }

      }

    }
    #endregion

  }

  /// <summary>
  /// Specifies the way to match a list value.
  /// </summary>
  public sealed partial class ListMatcher : pb::IMessage<ListMatcher> {
    private static readonly pb::MessageParser<ListMatcher> _parser = new pb::MessageParser<ListMatcher>(() => new ListMatcher());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ListMatcher> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Envoy.Type.Matcher.ValueReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListMatcher() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListMatcher(ListMatcher other) : this() {
      switch (other.MatchPatternCase) {
        case MatchPatternOneofCase.OneOf:
          OneOf = other.OneOf.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListMatcher Clone() {
      return new ListMatcher(this);
    }

    /// <summary>Field number for the "one_of" field.</summary>
    public const int OneOfFieldNumber = 1;
    /// <summary>
    /// If specified, at least one of the values in the list must match the value specified.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Type.Matcher.ValueMatcher OneOf {
      get { return matchPatternCase_ == MatchPatternOneofCase.OneOf ? (global::Envoy.Type.Matcher.ValueMatcher) matchPattern_ : null; }
      set {
        matchPattern_ = value;
        matchPatternCase_ = value == null ? MatchPatternOneofCase.None : MatchPatternOneofCase.OneOf;
      }
    }

    private object matchPattern_;
    /// <summary>Enum of possible cases for the "match_pattern" oneof.</summary>
    public enum MatchPatternOneofCase {
      None = 0,
      OneOf = 1,
    }
    private MatchPatternOneofCase matchPatternCase_ = MatchPatternOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MatchPatternOneofCase MatchPatternCase {
      get { return matchPatternCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearMatchPattern() {
      matchPatternCase_ = MatchPatternOneofCase.None;
      matchPattern_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ListMatcher);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ListMatcher other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(OneOf, other.OneOf)) return false;
      if (MatchPatternCase != other.MatchPatternCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (matchPatternCase_ == MatchPatternOneofCase.OneOf) hash ^= OneOf.GetHashCode();
      hash ^= (int) matchPatternCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (matchPatternCase_ == MatchPatternOneofCase.OneOf) {
        output.WriteRawTag(10);
        output.WriteMessage(OneOf);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (matchPatternCase_ == MatchPatternOneofCase.OneOf) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OneOf);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ListMatcher other) {
      if (other == null) {
        return;
      }
      switch (other.MatchPatternCase) {
        case MatchPatternOneofCase.OneOf:
          if (OneOf == null) {
            OneOf = new global::Envoy.Type.Matcher.ValueMatcher();
          }
          OneOf.MergeFrom(other.OneOf);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Envoy.Type.Matcher.ValueMatcher subBuilder = new global::Envoy.Type.Matcher.ValueMatcher();
            if (matchPatternCase_ == MatchPatternOneofCase.OneOf) {
              subBuilder.MergeFrom(OneOf);
            }
            input.ReadMessage(subBuilder);
            OneOf = subBuilder;
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
